### ISSUE TITLE
chexpert pre-trained 

### ISSUE THREAD

**Issue by xcharxlie** [JuliaWolleb/diffusion-anomaly#13]
Thanks for your great work. We are researchers trying to develop something based on your model, do you mind sharing the Chexpert pre-trained classifier and diffusion models to reproduce results? Thank you so much!

**Comment by JuliaWolleb** [comment]
Please find the pre-trained models for the Chexpert dataset under this link:
https://www.dropbox.com/sh/up4sqmeqrlwrxkw/AACqgnSCR8p20r6aO_3_Jy94a?dl=0

**Comment by xcharxlie** [comment]
Thank you so much!
