### ISSUE TITLE
How many. steps did you use to train cheapest?

### ISSUE THREAD

**Issue by Junyiliu0** [JuliaWolleb/diffusion-anomaly#20]
Hi
Can you tell me how iterations did you use for training the chexpert_dataset? I found maybe the batch size of the cheapest_dataset is 1. And how long cost?
Besides,
I found there will be two .pt file during training.
<img width="271" alt="image" src="https://github.com/JuliaWolleb/diffusion-anomaly/assets/100564143/e7db54e0-d1e5-4d45-b758-4d307232d539">
Which one should I choose during testing? What is meaning of ema?
Hope your reply!
Thanks!

**Comment by JuliaWolleb** [comment]
Good morning

As written in the paper, we train our models for 20,000 iterations (but you can always train longer...). It takes about one day.
"ema" means exponential moving average of the model parameters. I chose the one without ema, but choosing ema is alsow fine.

Best

**Comment by Junyiliu0** [comment]
Thank a lot!
