### ISSUE TITLE
Sampling model details

### ISSUE THREAD

**Issue by njan-creative** [JuliaWolleb/diffusion-anomaly#4]
The command for generating the samples are given as below.

python scripts/classifier_sample_known.py  --data_dir path_to_testdata  --model_path ./results/model.pt --classifier_path ./results/classifier.pt --dataset brats_or_chexpert --classifier_scale 100 --noise_level 500 $MODEL_FLAGS $DIFFUSION_FLAGS $CLASSIFIER_FLAGS  $SAMPLE_FLAGS 

There are two model paths in the command.. 

1.  --model_path ./results/model.pt
2. --classifier_path ./results/classifier.pt

On training the below series of '.pt' files were generated in the results folder.
brats2update2500000.pt	
emabrats2update_0.9999_2550000.pt
modelbratsclass025000.pt
optbratsclass025000.pt

Can you please specify the paths to use for model and classier in the command above.

**Comment by JuliaWolleb** [comment]
Hi

You will need the model "brats2update2500000.pt" as diffusion model (model_path), and the "modelbratsclass025000.pt" as classifier model (classifier_path)
