### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by njan-creative** [JuliaWolleb/diffusion-anomaly#7]
Can you share the pretrained models for reproducing the results.

**Comment by JuliaWolleb** [comment]
https://www.dropbox.com/sh/up4sqmeqrlwrxkw/AACqgnSCR8p20r6aO_3_Jy94a?dl=0
these are the diffusion model and the classifier for the brats dataset

**Comment by njan-creative** [comment]
Thanks for the response.. 
Will download and check.
